version: '3'
services:
    postgres:
        image: postgres:latest
        container_name: postgres
        ports:
          - "5432:5432"
        environment:
            - LC_ALL=C.UTF-8
            - POSTGRES_DB=terawhars
            - POSTGRES_USER=terawhars
            - POSTGRES_PASSWORD=terawhars
            - POSTGRES_PORT=5432
    wildfly:
        image: terawhars
        container_name: wildfly
        build: .
        ports:
            - "8080:8080"
            - "9990:9990"
        environment:
            - DB_HOST=postgres
            - DB_PORT=5432
            - DB_NAME=terawhars
            - DB_USER=terawhars
            - DB_PASS=terawhars
            - DS_NAME=TeraWHARSDS
            - JNDI_NAME=java:jboss/datasources/TeraWHARSDS
        depends_on:
            - postgres
        volumes:
            - jboss-conf:/opt/jboss/wildfly/standalone/deployments
    pgAdmin:
        image: dpage/pgadmin4:latest
        container_name: pgAdmin
        ports:
            - "5555:80"
        environment:
            - PGADMIN_DEFAULT_EMAIL=pedro@illaisaca.com
            - PGADMIN_DEFAULT_PASSWORD=pedro@illaisaca.com
        depends_on:
            - postgres
        volumes:
            - volumePG_Admin:/var/lib/pgadmin
volumes:
    jboss-conf:
    volumePG_Admin:
        external: true

